version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - antialiasing
  - Arie
  - backgrounding
  - boundwitness
  - breakpad
  - codacy
  - codeclimate
  - customizer
  - Foreventory
  - huri
  - keychain
  - networkidle
  - pako
  - printenv
  - proxied
  - repost
  - sandboxing
  - snyk
  - swiftshader
  - templating
  - Trouw
  - xylabs
  - XYO
ignoreWords: []
import: []
