// Aggregated from a bunch of places like:
// - https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
// - https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers
// - https://github.com/microsoft/vscode/blob/main/src/vs/platform/webview/common/mimeTypes.ts
// etc.

export const knownFileExtensions: Record<string, true | undefined> = {
  '.3gp': true,
  '.aac': true,
  '.apng': true,
  '.avif': true,
  '.bmp': true,
  '.cjs': true,
  '.css': true,
  '.cts': true,
  '.cur': true,
  '.es6': true,
  '.flac': true,
  '.gif': true,
  '.htm': true,
  '.html': true,
  '.ico': true,
  '.icon': true,
  '.jfif': true,
  '.jpeg': true,
  '.jpg': true,
  '.js': true,
  '.json': true,
  '.jsx': true,
  '.m4': true,
  '.m4a': true,
  '.m4p': true,
  '.md': true,
  '.mjs': true,
  '.mov': true,
  '.mp': true,
  '.mp3': true,
  '.mpeg': true,
  '.mts': true,
  '.oft': true,
  '.og': true,
  '.ogg': true,
  '.pac': true,
  '.pjp': true,
  '.pjpeg': true,
  '.png': true,
  '.svg': true,
  '.tif': true,
  '.tiff': true,
  '.ts': true,
  '.tsx': true,
  '.ttf': true,
  '.txt': true,
  '.wasm': true,
  '.wav': true,
  '.webm': true,
  '.webp': true,
  '.woff': true,
  '.woff2': true,
  '.xhtml': true,
  '.xml': true,
}
